version: "3.3"  #docker version>=18.02.0+

services:
  godnslog:
    depends_on:
      - db
    image: sort/godnslog
    container_name: godnslog
    command: serve -domain yourdomain.com -4 x.x.x.x -driver mysql -dsn 'godnslog:godnslog123@tcp(db:3306)/godnslog?charset=utf8'
    ports:
      - "8080:8080"    # reverseProxy
      - "53:53/udp"
    environment:
      - GIN_MODE=release
    restart: always

  db:
    image: mysql:5.7
    container_name: godnslog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: godnslogPASS
      MYSQL_USER: godnslog
      MYSQL_PASSWORD: godnslog123
      MYSQL_DATABASE: godnslog
      MYSQL_ROOT_HOST: "0.0.0.0"
    volumes:
       - godnslog-mysql-data:/var/lib/mysql
       #- ./mysql:/docker-entrypoint-initdb.d/
  
volumes:
  godnslog-mysql-data:
